%YAML 1.2
---
- name: dependencies for node
  apt: pkg={{item}}
       state=present
  with_items:
  - make
  - gcc
  - g++
  - openssl
  sudo: yes
  tags: node

- name: create temp folder
  file: path=/home/{{user}}/tmp state=directory mode=755
  tags: node

- name: get node {{version}}
  get_url: url=http://nodejs.org/dist/v{{version}}/node-v{{version}}.tar.gz
           dest=/home/{{user}}/tmp/node-v{{version}}.tar.gz
           force=no
  tags: node

- name: unpack node
  command: /bin/tar xzf node-v{{version}}.tar.gz
           chdir=/home/{{user}}/tmp
           creates=/home/{{user}}/tmp/node-v{{version}}
  tags: node

- name: build node
  command: ./configure && /usr/bin/make
           chdir=/home/{{user}}/tmp/node-v{{version}}
  sudo: yes
  tags: node

- name: install node
  command: /usr/bin/make install
           chdir=/home/{{user}}/tmp/node-v{{version}}
  sudo: yes
  tags: node
